nelmio_api_doc:
    documentation:
        info:
            title: Tasklist app
            description: Demo tasklist app
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc|/doc\.json$) # Accepts routes under /api except /api/doc
